title: The Haven
description: "a journal of thoughts"
baseurl: /
homepage: https://blog.dylaniskandar.com
highlighter:      pygments
permalink:        pretty
paginate:         5
excerpt_separator: <!--more-->
about: https://dylaniskandar.com
